services:
  db_test:
    image: mariadb
    hostname: test
    environment:
      MYSQL_ROOT_PASSWORD: pf$$6#iAEQ#@y7vMnXiTXLLC#wiEHcn
      MYSQL_DATABASE: test
      MYSQL_USER: manager_test
      MYSQL_PASSWORD: RqoKdtp88Z94v7vL#XKVHPxWdb9dw
    volumes:
      - ./Base de datos/test.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    networks:
      - red_taller_software

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    container_name: grupo5_backend
    depends_on:
      - db_test
    networks:
      - red_taller_software
    environment:
      - PORT=4005
      - ORIGIN=http://grupo5.146.83.216.166.nip.io
      - DB_HOST=db_test
      - DB_PORT=3306
      - DB_USER=manager_test
      - DB_PASSWORD=RqoKdtp88Z94v7vL#XKVHPxWdb9dw
      - DB_NAME=test

  frontend:
    build:
      context: ./Frontend
      dockerfile: ./dockerfile
    container_name: grupo5_frontend
    networks:
      - red_taller_software
    env_file:
      - ./Frontend/.env

volumes:
  data:
    external: false

networks:
  red_taller_software:
    external: true